### PR TITLE
Incremental Page Loading and Reloading

### PR DESCRIPTION
**Pull request by kralverde**
This PR aims to alleviate page failures with incremental fetch requests and allows for a key to reload a page if needed. Would like some input if there's a better way to do this. Should just add parameters to the config file?

Also I noticed that there is significant lag when switching pages, and I'm not sure if it's because of this or running in debug mode.

### CODE REVIEW

**Comment by josueBarretogit** [comment]
Hi thanks for your contribution I just tested locally and I really like what you did

> Would like some input if there's a better way to do this. Should just add parameters to the config file?

by parameters you mean the amount of pages loaded?  also I think your implementations is really good I for one didn´t know how to do this. 

> Also I noticed that there is significant lag when switching pages, and I'm not sure if it's because of this or running in debug mode.

I always run `cargo run --release` not sure if its a bad practice and I don´t notice any lag

**Comment by kralverde** [comment]
Yeah, mainly the amount of pages loaded and when to load more pages

**Comment by josueBarretogit** [comment]
I'm making changes to the reader page in this pr #42 and things like the image quality are taken care of, so just focus on the incremental loading, also the user can go from the page 1 to the last and when I do that the page isn't loaded, so I think it's better to change this so that this "going around" behavior doesn´t happen.

> Yeah, mainly the amount of pages loaded and when to load more pages

ok so in order to add a new variable to the config file let's call it `amount_pages` it's necessary
- Add `amount_pages` to struct `MangaTuiConfig`
- read already existing config which is outated, it's missing `amount_pages`
- append this new variable and preserve the other ones

I haven't defined this behavior so I think it's better to keep it on another pr

**Comment by kralverde** [comment]
Ok, I'll wait until you merge that PR, and then I'll rebase before opening the PR

**Comment by kralverde** [comment]
Should be good to go now

**Comment by josueBarretogit** [comment]
Remember to run `cargo test -- --ignored` as well

**Comment by kralverde** [comment]
should be good to go now (pt 2)

**Comment by josueBarretogit** [comment]
@kralverde Changed target branch to `develop_v0.4.0` I need to add the option to bookmark chapter from reader page so I want to merge what you did before continuing

**Comment by kralverde** [comment]
rebased, should be good

**Comment by kralverde** [comment]
wait i broke something in the rebase

**Comment by kralverde** [comment]
fixed

**Comment by josueBarretogit** [comment]
Many thanks I really appreciate the effort you put into this pr, sorry for any inconveniences

**Comment by kralverde** [comment]
No inconvenience. I'll probably make a few more PRs if that's ok :p

**Pull request merged**
